// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt2NqBzmo0xFS7Cg4L68zX0sQKgXlrWMo',
    appId: '1:218386353764:web:e32524aa3edb3ec5ebd971',
    messagingSenderId: '218386353764',
    projectId: 'evently-42c34',
    authDomain: 'evently-42c34.firebaseapp.com',
    storageBucket: 'evently-42c34.firebasestorage.app',
    measurementId: 'G-RL1SNTWE1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO4X9yuvN6NPnSW8_oaL0SmiRr90V51as',
    appId: '1:218386353764:android:524133163b2dc2e5ebd971',
    messagingSenderId: '218386353764',
    projectId: 'evently-42c34',
    storageBucket: 'evently-42c34.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOgwF9SwN-7cWBNA5HjIVSC1p6aUGHUHk',
    appId: '1:218386353764:ios:baee88db16e106c8ebd971',
    messagingSenderId: '218386353764',
    projectId: 'evently-42c34',
    storageBucket: 'evently-42c34.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOgwF9SwN-7cWBNA5HjIVSC1p6aUGHUHk',
    appId: '1:218386353764:ios:baee88db16e106c8ebd971',
    messagingSenderId: '218386353764',
    projectId: 'evently-42c34',
    storageBucket: 'evently-42c34.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt2NqBzmo0xFS7Cg4L68zX0sQKgXlrWMo',
    appId: '1:218386353764:web:8a1dbce1c2e08e69ebd971',
    messagingSenderId: '218386353764',
    projectId: 'evently-42c34',
    authDomain: 'evently-42c34.firebaseapp.com',
    storageBucket: 'evently-42c34.firebasestorage.app',
    measurementId: 'G-C3ZKMWPMYV',
  );
}
